name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'appointment-api/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'appointment-api/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: appointment-api
    steps:
      - uses: actions/checkout@v6

      - name: Instalar Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Instalar dependências e Compilar
        run: mvn clean install -DskipTests
